name: Project Build Windows

on:
  workflow_call:

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ilammy/msvc-dev-cmd@v1.12.1
    - name: update-workspace
      shell: pwsh
      run: |
        mkdir bin_x64
        mkdir bin_x64/data
    - name: build-project
      run: |
        cmake --preset win-relwithdebinfo
        cmake --build --preset win-relwithdebinfo --target cizzcdzz -j $env:NUMBER_OF_PROCESSORS