name: Project Build Linux

on:
  workflow_call:

jobs:
  build:
    name: run on linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: update-workspace
      run: |
        sudo apt -qq update
        sudo apt install --yes cmake build-essential libgl1-mesa-dev libssl-dev
    - name: build-project
      run: |
        mkdir linux_build
        mkdir linux_build/data
        cmake --preset linux-gcc-release-make
        cmake --build --preset linux-gcc-release-make -- -j$(nproc)